cargo-features = ["strip"]

[package]
name = "bulk-mkv-manipulation"
version = "0.1.0"
authors = ["Ryan Jones-Ward <sciguyryan@gmail.com>"]
edition = "2021"
readme = "README.md"
description = "An automatic bulk MKV manipulation tool."
license = "LGPL 2.1"
repository = "https://github.com/sciguyryan/Bulk-MKV-Manipulation"
homepage = "https://github.com/sciguyryan/Bulk-MKV-Manipulation"
build = "build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.139"
serde_derive = "1.0.139"
serde_json = "1.0.74"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
strip = true
#panic = "abort"
